rv1106_ipc: CMakeLists.txt: fix build with static link
arm-rockchip830-linux-uclibcgnueabihf/bin/ld.bfd: output/out/media_out/lib/librkaiq.a(cac_adaptor.cpp.o): undefined reference to symbol '_ZNSt14basic_ifstreamIcSt11char_traitsIcEEC1EPKcSt13_Ios_Openmode@@GLIBCXX_3.4'
arm-rockchip830-linux-uclibcgnueabihf/bin/ld.bfd: tools/linux/toolchain/arm-rockchip830-linux-uclibcgnueabihf/bin/../lib/gcc/arm-rockchip830-linux-uclibcgnueabihf/8.3.0/../../../../arm-rockchip830-linux-uclibcgnueabihf/lib/libstdc++.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status

Signed-off-by: Weiwen Chen <cww@rock-chips.com>
Change-Id: Idf412312b5baca77cf1d4d87fbc92a126b4c73f1